### ISSUE TITLE
IOError: [Errno socket error] [Errno 65] No route to host

### ISSUE THREAD

**Issue by winterbang** [digitalfruit/limejs#156]
### When i execute _bin/lime.py init_, i get this error bellow

> Downloading Closure Compiler: 
> Traceback (most recent call last):
>   File "bin/lime.py", line 436, in <module>
>     main()
>   File "bin/lime.py", line 417, in main
>     checkDependencies()
>   File "bin/lime.py", line 120, in checkDependencies
>     urlretrieve("http://closure-compiler.googlecode.com/files/compiler-20130411.zip",zip_path,rephook)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 98, in urlretrieve
>     return opener.retrieve(url, filename, reporthook, data)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 245, in retrieve
>     fp = self.open(url, data)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 213, in open
>     return getattr(self, name)(url)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 350, in open_http
>     h.endheaders(data)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1049, in endheaders
>     self._send_output(message_body)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 893, in _send_output
>     self.send(msg)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 855, in send
>     self.connect()
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 832, in -connect
>     self.timeout, self.source_address)
>   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 575, in create_connection
>     raise err
> IOError: [Errno socket error] [Errno 65] No route to host

**Comment by gaoyangyiqiao** [comment]
I get the same problem.Have you fix it?
