### ISSUE TITLE
unzipping error when im bin\lime.py init

### ISSUE THREAD

**Issue by rwsodinz** [digitalfruit/limejs#158]
Downloading Closure Compiler:
515%
Unzipping...
Traceback (most recent call last):
  File "C:\limejs\bin\lime.py", line 436, in <module>
    main()
  File "C:\limejs\bin\lime.py", line 417, in main
    checkDependencies()
  File "C:\limejs\bin\lime.py", line 122, in checkDependencies
    zippedFile = zipfile.ZipFile(zip_path)
  File "C:\Python27\lib\zipfile.py", line 770, in **init**
    self._RealGetContents()
  File "C:\Python27\lib\zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file

**Comment by rsalvo78** [comment]
Hi rwsodinz, just submitted a pull request to fix this: #160. 
I made a change to a few lines in the "lime.py" file to download the correct Closure Compiler.

**Comment by Corbineau** [comment]
I'm having this same issue now.
